config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :users
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'admin', to: 'admin#index'
  resources :support_requests, only: %i[index update]
  scope '(:locale)' do
    get "store/index"
    root "store#index"
    resources :carts
    resources :orders
    resources :line_items do
      member do 
        patch :update_quantity
      end
    end
  end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
      current_item.quantity = 1
    end
    current_item
  end

  def update_quantity(line_item_id, quantity)
    line_item = line_items.find(line_item_id)
    if line_item
      line_item.quantity = quantity
    end
    line_item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: %i[ create update destroy ]
  before_action :set_cart, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :cart_not_found

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    redirect_to store_index_path, notice: "Access denied." unless @cart.id == session[:cart_id]
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy! if @cart.id === session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_index_path, status: :see_other, notice: "Cart was empty." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_not_found
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_path, notice: "Invalid cart"
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>" class="w-full sm:w-auto my-8 space-y-5">
  <div class="overflow-x-auto rounded-xl bg-white">
    <table class="min-w-full table-auto text-sm text-left border-separate border-spacing-y-1">
      <thead>
        <tr class="text-gray-600 uppercase text-xs tracking-wider">
          <th class="px-4 py-2 text-right">Qty</th>
          <th class="px-4 py-2">Product</th>
          <th class="px-4 py-2 text-right">Price</th>
          <th class="px-4 py-2 text-center">Action</th>
        </tr>
      </thead>
      <tbody>
        <%= render cart.line_items %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="3" class="p-4 text-right text-base font-semibold text-gray-700">Total:</th>
          <td class="p-4 text-right text-base font-bold text-green-800" colspan="2">
            <%= number_to_currency(cart.total_price) %>
          </td>
        </tr>
      </tfoot>
    </table>
    <%= form_with url: new_order_path, method: :get, data: { controller: "checkout" } do %>
      <%= button_tag t(".checkout"),
      type: "submit",
      class: 'ml-4 rounded-lg py-1 px-2 text-black bg-green-200',
      data: {
        checkout_target: "button",
        action: "click->checkout#checkIfOnCheckoutPage"
      } %>
    <% end %>
  </div>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, class: "contents") do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul class="list-disc ml-6">
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<% content_for :title, "Editing cart" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing cart</h1>

  <%= render "form", cart: @cart %>

  <%= link_to "Show this cart", @cart, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to carts", carts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/carts/index.html.erb
<% content_for :title, "Carts" %>
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Your Carts</h1>
  </div>
  <div id="carts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @carts.any? %>
      <% @carts.each do |cart| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render cart %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", cart, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Empty Cart", cart, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No carts found.</p>
    <% end %>
  </div>
</div>

app/views/carts/new.html.erb
<% content_for :title, "New cart" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New cart</h1>

  <%= render "form", cart: @cart %>

  <%= link_to "Back to carts", carts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/carts/show.html.erb
<% content_for :title, "Showing cart" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Your cart</h1>

  <%= render @cart %>
  <%= button_to "Empty cart", @cart, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>